# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-06-11 10:34:38
"""
import arcpy
from sys import argv

Scratch_Workspace = arcpy.GetParameterAsText(0)
Output_Workspace = arcpy.GetParameterAsText(1)
Input_Features = arcpy.GetParameterAsText(2) # this needs to have multiple inputs
Output_Name = arcpy.GetParameterAsText(3)

def Union(Input_Features, union_output = fr"{Output_Workspace}\{Output_Name}"):  # Strata Union

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Process: Union (Union) (analysis)
    arcpy.analysis.Union(in_features=Input_Features, out_feature_class=union_output, join_attributes="NO_FID", cluster_tolerance="", gaps="GAPS")

    # Process: Repair Geometry (Repair Geometry) (management)
    union_output_3_ = arcpy.management.RepairGeometry(in_features=union_output, delete_null="KEEP_NULL", validation_method="ESRI")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=fr"{Scratch_Workspace}", workspace=r"{Output_Workspace}"):
        Union(*argv[1:])
